# https://starship.rs/config

[character]
symbol = "△"
vicmd_symbol = "▽"

[aws]
disabled = true

[package]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[git_branch]
symbol = ""
style = "white"

[git_status]
style = "white"
prefix = " "
suffix = " "
deleted = "×"

[directory]
style = "white"
