# https://starship.rs/config

[character]
success_symbol = "[△](bold green)"
error_symbol = "[×](bold red)"
vicmd_symbol = "[▽](bold green)"

[git_branch]
symbol = ""
style = "black"

[git_status]
style = "black"
deleted = "×"
format = "[$all_status$ahead_behind]($style) "
# this still takes a long time on large repositories
disabled = true

[directory]
style = "black"

[aws]
disabled = true

[golang]
disabled = true

[java]
disabled = true
