# https://starship.rs/config

[character]
success_symbol = "[△](bold green)"
error_symbol = "[×](bold red)"
vicmd_symbol = "[▽](bold green)"

[git_branch]
symbol = ""
style = "white"

[git_status]
style = "white"
deleted = "×"
format = "[$all_status$ahead_behind]($style) "

[directory]
style = "white"
