# https://starship.rs/config

# basically, trim down all the language / tool versions
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$battery\
$time\
$status\
$character"""

[character]
success_symbol = "[△](bold green)"
error_symbol = "[×](bold red)"
vicmd_symbol = "[▽](bold green)"

[git_branch]
symbol = ""
style = "black"

[git_status]
style = "black"
deleted = "×"
format = "[$all_status$ahead_behind]($style) "
# this still takes a long time on large repositories
disabled = true

[directory]
style = "black"
